### ISSUE TITLE
panic in github.com/djherbis/nio

### ISSUE THREAD

**Issue by danp** [oklog/oklog#16] opened 2017-01-17 15:03 UTC
Was doing a simple test as described in the [quickstart](https://github.com/oklog/oklog#quickstart). When querying, I got this panic from the ingeststore:

```
% ~/Downloads/oklog-0.1.0-darwin-amd64 ingeststore -store.segment-replication-factor 1
ts=2017-01-17T14:20:54Z level=info cluster=0.0.0.0:7659
ts=2017-01-17T14:20:54Z level=info fast=tcp://0.0.0.0:7651
ts=2017-01-17T14:20:54Z level=info durable=tcp://0.0.0.0:7652
ts=2017-01-17T14:20:54Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-01-17T14:20:54Z level=info API=tcp://0.0.0.0:7650
ts=2017-01-17T14:20:54Z level=info ingest_path=data/ingest
ts=2017-01-17T14:20:54Z level=info store_path=data/store
ts=2017-01-17T14:20:54Z level=debug component=cluster Join=0
panic: runtime error: slice bounds out of range

goroutine 1858 [running]:
github.com/djherbis/nio.(*PipeWriter).Write(0xc42000e050, 0xc4205ec99c, 0x1e, 0x664, 0x0, 0x0, 0x0)
	/Users/peter/src/github.com/djherbis/nio/sync.go:135 +0x30a
github.com/oklog/oklog/pkg/store.newConcurrentFilteringReadCloser.func1(0x2693d80, 0xc421f83620, 0xc42000e050, 0xc4200148c0)
	/Users/peter/src/github.com/oklog/oklog/pkg/store/query.go:265 +0x198
created by github.com/oklog/oklog/pkg/store.newConcurrentFilteringReadCloser
	/Users/peter/src/github.com/oklog/oklog/pkg/store/query.go:276 +0x210
```

Was running ingeststore like so:

```
% ~/Downloads/oklog-0.1.0-darwin-amd64 ingeststore -store.segment-replication-factor 1
```

a producer like so:

```
% while true; do echo hi; done | ~/Downloads/oklog-0.1.0-darwin-amd64 forward localhost
```

and this query:

```
% ~/Downloads/oklog-0.1.0-darwin-amd64 query -from 1m -v -q hi
-from 2017-01-17T10:25:07-04:00 -to 2017-01-17T10:26:07-04:00
Get http://localhost:7650/store/query?from=2017-01-17T10%3A25%3A07-04%3A00&to=2017-01-17T10%3A26%3A07-04%3A00&q=hi: EOF
```

Will try and dig in but perhaps you'll spot the problem sooner.

**Comment by peterbourgon** [comment] 2017-01-17 15:04
Ha! Fun. Thanks for that.

**Comment by danp** [comment] 2017-01-17 15:31
Opened https://github.com/djherbis/nio/pull/3.

**Comment by peterbourgon** [comment] 2017-01-17 15:35
Great spot!

**Comment by danp** [comment] 2017-01-17 16:16
PR merged! I suppose since go get [-u] will fetch the updated nio package this can be closed?

**Comment by peterbourgon** [comment] 2017-01-17 16:18
So fast! Let me reproduce and verify the fix, then I'll make an emergency v0.1.1 release ;) before closing this out.

**Comment by peterbourgon** [comment] 2017-01-17 16:29
Hmm. I can't reproduce on my machine. But I'll still vendor, capture the update, and make a new release.

**Comment by danp** [comment] 2017-01-17 16:45
Running `while true; do ~/Downloads/oklog-0.1.0-darwin-amd64 query -from 1m -v -q hi | head; done` while the ingest store and producer were also running repro'd it pretty reliably fwiw.

**Comment by djherbis** [comment] 2017-01-17 16:47
This should be fixed now, it was definitely a bug in djherbis/nio, thanks @danp for the pr!

**Comment by peterbourgon** [comment] 2017-01-17 16:54
@danp Would you mind confirming it's fixed in https://github.com/oklog/oklog/releases/tag/v0.1.1?

**Comment by danp** [comment] 2017-01-17 17:07
Seems good! I have been running it for 5+ minutes now which is way longer than the 0.1.0 binary lasted.

**Comment by peterbourgon** [comment] 2017-01-17 17:11
Good enough! 😎

**Closed by peterbourgon** 2017-01-17 17:11 UTC
