### ISSUE TITLE
bufio.Scanner: token too long

### ISSUE THREAD

**Issue by jozuenoon** [oklog/oklog#127] opened 2018-06-08 09:49 UTC
I'm seeing this error with long log lines:

`ts=2018-06-08T09:40:57.26666682Z level=error component=Consumer op=gather error="bufio.Scanner: token too long" msg="ingester 100.96.2.124:7650, during mergeRecords: fatal error"`

Thing is that it lockout whole cluster. Maybe those messages should be just dropped or maybe there is way to handle it ?

Similar issue: https://github.com/sirupsen/logrus/issues/564

**Comment by peterbourgon** [comment] 2018-06-08 20:19
Known issue and dupe of #21

I know this doesn't help much, but consider avoiding shipping log lines that are >64KB in size :)

**Closed by peterbourgon** 2018-06-08 20:19 UTC
