### ISSUE TITLE
Javascript error in UI on Firefox (TypeError on response.body at ports.js:68)

### ISSUE THREAD

**Issue by bartgrantham** [oklog/oklog#73] opened 2017-09-30 13:05 UTC
The actual error is "TypeError: response.body is undefined"

This is on FF 56.0 on MacOS 10.12.6.  I'm not familiar enough with Elm to know what the type of `response` in this function is supposed to be and if the lack of a `body` field is a normal occurrence, a browser-compatibility issue, or a framework bug.  Since it works on the same machine under Chrome, I'm leaning toward one of the latter two.

I'll try to dig deeper later.

PS - really like the project!

**Comment by peterbourgon** [comment] 2017-10-02 11:54
@xla

**Comment by xla** [comment] 2017-10-02 13:08
This is a duplicate of #68 and I would continue the dialogue there. Thanks for the report!

**Closed by xla** 2017-10-02 13:08 UTC
